server:
  port: 8081
  servlet:
    context-path: /api/v1/contactmanager-service

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:config/liquibase/master.yaml
    enabled: true
    liquibase-schema: public



springdoc:
 swagger-ui:
   path: /swagger-ui.html
   enabled: true

logging:
  level:
    root: info
